Title: William Anto
Logo: 20250429_145508.jpg
Description: Data analyst with two years experience in report automation using Advance Excel, Data manipulation and interogation in SQL and Business Interlligence Report on Power BI.
# show_downloads: true
# google_analytics:
theme: jekll-theme-minimal
